# Generated by Django 5.1.2 on 2024-11-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles_app', '0003_alter_profile_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
