# Generated by Django 5.1.2 on 2024-11-13 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles_app', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles_app.category'),
        ),
    ]
