# Generated by Django 5.1.2 on 2024-11-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles_app', '0005_alter_category_name_alter_tile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='stock',
            field=models.IntegerField(default=100),
        ),
    ]
